### PR TITLE
Fixes #6533: Move ncf examples out of the main tree to prevent errors in...

### PR DESCRIPTION
**Pull request by Kegeruneku**
... ncf-builder

Ticket: http://www.rudder-project.org/redmine/issues/6533

To be merged in master

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
I think the services and the knowledge should be put in examples too!

**Comment by Kegeruneku** [comment]
Not sure about that... Don't we reference them in quickstarts / demos ?

**Comment by VinceMacBuche** [comment]
We should update demo to tell to use examples it would be better

**Comment by VinceMacBuche** [comment]
Can you open an issue about that, removing techniques is more important that having good services/knowledge.

**Comment by VinceMacBuche** [comment]
So i can merge this and we still track down that issue

**Comment by Kegeruneku** [comment]
PR updated.

**Pull request merged**
