### PR TITLE
Update file_ensure_lines_present.cf

### PR DESCRIPTION
**Pull request by VinceMacBuche**

### CODE REVIEW

**Comment by amousset** [comment]
I think it may break reporting with several editions on the same file as the reports only differ by the inserted content, and some of them might not be done is the message is exactly the same.

**Comment by VinceMacBuche** [comment]
we could add the lines in the promiser

**Comment by VinceMacBuche** [comment]
or generate id on the promiser

**Comment by VinceMacBuche** [comment]
Done in #837

**Pull request closed without merging**
