### PR TITLE
Fixes #8691: Add bodies to manage AIX password files

### PR DESCRIPTION
**Pull request by ncharles**
https://www.rudder-project.org/redmine/issues/8691

### CODE REVIEW

**Comment by peckpeck** [comment]
Good, merging

**Comment by ncharles** [comment]
need to be updated, as it won't create the entries

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
OK, merging this PR

**Comment by ncharles** [comment]
OK, merging this PR

**Pull request merged**
