### PR TITLE
Fixes #9187: logger_rudder evaluates at each call the expected_reports_temp file

### PR DESCRIPTION
**Pull request by ncharles**
https://www.rudder-project.org/redmine/issues/9187

### CODE REVIEW

**Comment by ncharles** [comment]
still testing, do not merge

**Comment by ncharles** [comment]
tested, looks ok - on a small test system with standart directive + 3 ncf techniques with a total of 19 components, run length went from 11s to 9s

**Comment by amousset** [comment]
Could we add something like this at the beginning of the bundle?

```
  # The different files used for reporting are:
  # * expected_reports_source: part of the promises, generated on the server
  # * expected_reports_temp: temporary file templated from expected_reports_source
  # * expected_reports_file: final file, generated from the content of expected_reports_temp
  #
  # The general workflow during the first call to logger_rudder of each run is:
  # 1/ Read the report file present in the promises (expected_reports_source),
  #    and expand it into the temporary report file (expected_reports_temp)
  # 2/ Read the content of the temporary file into a variable (reports)
  # 3/ Using the content of the read variable, write the content of the final file
  # 4/ Read the content of the final file into another variable (report_data), and use it for actual reporting
  #
  # The workflow for the other calls is only:
  #  4/ Read the content of the final file into another variable (report_data), and use it for actual reporting
```

**Comment by ncharles** [comment]
Commit modified

**Comment by ncharles** [comment]
it's done

**Comment by ncharles** [comment]
OK, merging this PR

**Pull request merged**
