### PR TITLE
Fixes #25778: Logger v4.1 with iterator support

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/25778

### CODE REVIEW

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
PR updated with a new commit

**Review by Fdall — APPROVED** [review]

**Pull request merged**
