### PR TITLE
Fixes #15178: In technique editor, deleting a new technique crashes

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/15178

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Why doing this instead of just remove delete option from actions?

**Comment by RaphaelGauthier** [comment]
You're right, we should do that instead.

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Comment by RaphaelGauthier** [comment]
OK, merging this PR

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Pull request merged**
