### PR TITLE
Fixes #16181: Missing edit_lines promises in dry-run lib

### PR DESCRIPTION
**Pull request by amousset**
https://issues.rudder.io/issues/16181

### CODE REVIEW

**Comment by ncharles** [comment]
why are you removing the user_dry_run, plus all the *_dry_run ?

**Comment by amousset** [comment]
These classes were mainly targetting ncf users outside of Rudder, we never actually used them. I think we have no need for them and it makes the code more readable.

**Comment by amousset** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
@ncharles updated

**Pull request merged**
