### PR TITLE
Fixes #7864: Add new checks for special file types

### PR DESCRIPTION
**Pull request by matya**
Check for File being FIFO/Socket/Symlink

### CODE REVIEW

**Comment by jooooooon** [comment]
This is a very promising contribution, thanks @matya!

In the interest of staying DRY, it would be preferable to create a 4th generic method, that takes an additional parameter "type", so that all logic is in that bundle, and it just compares the type with the type passed by parameter. That way, the 3 methods you have added here can just be wrappers for this inner method, and none of the logic is duplicated.

See file_copy_from_local_source for a simple example.

**Comment by matya** [comment]
Will check it out tomorrow

**Comment by matya** [comment]
Ok took me quite some time to figure out what you were doing using the new feature of the not always defined this.callers_promisers and copying old and new classes together... Stick not sure I understood all of it, might came back with some questions...

**Comment by jooooooon** [comment]
Ah, yes, that is some confusing s**t. I would recommend targeting your PR to the 0.x branch for now, and not worrying about that stuff (it's only on master)

**Comment by matya** [comment]
retargeting to v0.x

**Comment by matya** [comment]
@jooooooon See https://github.com/Normation/ncf/pull/318

**Pull request closed without merging**
