### PR TITLE
Fixes #15507: Remove remaining function about delete api

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/15507

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
There is no hooks anymore, they were only used as internal rudder purpose and we decided to not port it to Rudder code

**Comment by ncharles** [comment]
So you need to remove the mention of them on the README.md

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by VinceMacBuche** [comment]
yes, that what i did

**Comment by VinceMacBuche** [comment]
Commit modified

**Pull request merged**
