### PR TITLE
Fixes #11840: Add a variable from template generic method

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/11840

### CODE REVIEW

**Comment by amousset** [comment]
Indeed, set the issue back to *in progress*.

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
This need tests but should go in Rudder 6.1.x

**Comment by Fdall** [comment]
This is not really needed. Closing as I will not update it before a long time

**Pull request closed without merging**
