### PR TITLE
Fixes #7377: Adapt rudderify script to use <FILE> in the generated metadata.xml

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://www.rudder-project.org/redmine/issues/7377

### CODE REVIEW

**Comment by fanf** [comment]
Specification are on the moove for that one, perhaps we are going to only accept files under configuration-repository, and "/var/rudder/configuration-repository" will need to be changed to "RUDDER_CONFIGURATION_REPOSITORY". Not decided yet.

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by VinceMacBuche** [comment]
PR updated

**Pull request merged**
