### PR TITLE
Fixes #21412: Add documentation for package_present update cache

### PR DESCRIPTION
**Pull request by ElaadF**
https://issues.rudder.io/issues/21412

### CODE REVIEW

**Comment by ElaadF** [comment]
Commit modified

**Comment by ElaadF** [comment]
Commit modified

**Comment by ElaadF** [comment]
PR updated with a new commit

**Comment by ElaadF** [comment]
PR updated with a new commit

**Review by amousset — APPROVED** [review]

**Comment by ElaadF** [comment]
OK, squash merging this PR

**Pull request merged**
