### PR TITLE
Fixes #12430: Add a test to check the args variables matches the arguments of the generic methods

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/12430

### CODE REVIEW

**Comment by peckpeck** [comment]
Is this run automatically by qa_test ?

**Comment by amousset** [comment]
Yes, and it will currently fail, I will amend the PR to make the required fixes.

**Comment by peckpeck** [comment]
ping @amousset

**Comment by amousset** [comment]
Closing for now, this needs more work.

**Pull request closed without merging**
