### PR TITLE
Fixes #7261: When a generic method is modified (add parameter), method calls arenot updated

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://www.rudder-project.org/redmine/issues/7261

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by jooooooon** [comment]
Ping @VinceMacBuche @fanf ? This looks like an important bug fix that hasn't been merged

**Comment by VinceMacBuche** [comment]
I have rebased this, @fanf can you review it please ?

**Comment by ncharles** [comment]
@VinceMacBuche could you rebase it (again) please ?

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by VinceMacBuche** [comment]
ping @fanf

**Comment by VinceMacBuche** [comment]
PR updated

**Pull request merged**
