### PR TITLE
Fixes #12640: Fix pylint error in ncf 4.1

### PR DESCRIPTION
**Pull request by peckpeck**
https://www.rudder-project.org/redmine/issues/12640

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
Nothing to do on ncf file ? (at the root of the project, which was missing traceback ...)

**Comment by VinceMacBuche** [comment]
Ok, done here! https://github.com/Normation/ncf/pull/756 

have you check ncf file with pylint ?

**Comment by peckpeck** [comment]
OK, merging this PR

**Comment by peckpeck** [comment]
OK, merging this PR

**Pull request merged**
