### PR TITLE
Fixes #15208: Add  a file_check_line_match_regex GM

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/15208

### CODE REVIEW

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
Commit modified

**Comment by Fdall** [comment]
PR rebased

**Comment by Fdall** [comment]
Commit modified

**Comment by amousset** [comment]
Needs tests before merge.

**Comment by Fdall** [comment]
This was meant for cis plugin. It does not seem relevant anymore

**Pull request closed without merging**
