### PR TITLE
Fixes #15447: Improve zypper pattern error log

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/15447

### CODE REVIEW

**Comment by Fdall** [comment]
Commit modified

**Comment by amousset** [comment]
What kind of output does this produce?

**Comment by Fdall** [comment]
> What kind of output does this produce?

I added a screenshot taken in 5.0 on the redmine ticket.
Could not try if it was correctly reported in 5.1 as a report log yet

**Comment by amousset** [comment]
This is great! Thanks!

**Comment by Fdall** [comment]
PR rebased

**Comment by amousset** [comment]
Could you update from upstream now it is merged?

**Comment by Fdall** [comment]
Ah! well spotted.
It shoud be ok to merge in 5.0 but will be quite useless since the feature is to upload the error message to the webapp in a log_report.

We should be fine to update in 5.0 anyway

**Comment by Fdall** [comment]
PR replaced by https://github.com/Normation/ncf/pull/1093

**Pull request closed without merging**
