### PR TITLE
Fixes #13608: 

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://www.rudder-project.org/redmine/issues/13608

### CODE REVIEW

**Comment by peckpeck** [comment]
Won't we loose some logs with this solution ?

**Comment by VinceMacBuche** [comment]
Yes, we talked about it last week .... We need to do something else to force reporting

**Comment by VinceMacBuche** [comment]
put all variables in promiser or generate an id in all methods

**Comment by VinceMacBuche** [comment]
and use it everywhere and do it log too

**Comment by VinceMacBuche** [comment]
But I think we need to work with @amousset on this

**Comment by VinceMacBuche** [comment]
PR rebased

**Pull request merged**
