### PR TITLE
Fixes #22243: Missing cf-promises binary to run the ncf 'quick' tests

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/22243

### CODE REVIEW

**Comment by Fdall** [comment]
Commit modified

**Comment by Fdall** [comment]
Commit modified

**Review by VinceMacBuche — APPROVED** [review]

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
OK, squash merging this PR

**Pull request merged**
