### PR TITLE
Fixes #8638: file_ensure_lines_present_in_ini_section.cf test fails with CFEngine 3.9

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/8638

### CODE REVIEW

**Comment by amousset** [comment]
Still untested and undocumented, but do you see a better way of doing this?

**Comment by amousset** [comment]
Commit modified

**Comment by ncharles** [comment]
ha, somehow I didn't see that is was still untested (comment didn't appear?)

**Comment by amousset** [comment]
Now ready for review!

**Comment by amousset** [comment]
OK, merging this PR

**Pull request merged**
