### PR TITLE
Fixes #17113: Copy_from bundles are no longer keeping perms by default

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/17113

### CODE REVIEW

**Comment by amousset** [comment]
There are probably similar bodies in 5.0 techniques

**Comment by amousset** [comment]
We also need to check in ncf ncf as we moved bodies from techniques to ncf

**Comment by Fdall** [comment]
We still need to double check the remote_copy current behaviour before merging

**Comment by ncharles** [comment]
this looks much saner, but I'm pretty sure it will change a lot of behaviour. Notably when we are copying from server and then changing permissions. We'll always have repaired in this case

**Pull request closed without merging**
