### PR TITLE
rename class_prefix

### PR DESCRIPTION
**Pull request by frbayart**
rename class_prefix to package_verify_version to avoid conflit with package_install

### CODE REVIEW

**Comment by peckpeck** [comment]
This method calls package_install_version_cmp which effectively uses the package_install class prefix.
Removing the class prefix in the method metadata is not sufficient to change the prefix.

**Comment by frbayart** [comment]
Ok so I'm lucky because my update fix my problem, I'm now able to use class condition on package verify.

What is the clean solution to avoid conflict between classname in packages methods ?

**Comment by peckpeck** [comment]
There is no clean solution ready yet.
The problem is that they all use the same method in fine and this methods has a static class_prefix.
The solution is to have a class_prefix that depends on the call stack, that's why there is now and old_class_prefix and a new class_prefix in the code.

But this feature will only be available when the caller promiser patch will be merged into cfengine. 
We didn't include this patch in Rudder because we are not yet sure if it will be taken in the current form. The original PR is here https://github.com/cfengine/core/pull/2301

**Comment by frbayart** [comment]
so we can only use one "package" methods by techniques in ncf editor.

This news is very disappointing !

**Comment by peckpeck** [comment]
Sorry, this is a very longstanding bug in ncf that depends on the way it was designed and on a missing feature in cfengine.

**Pull request closed without merging**
