### PR TITLE
Fixes #18178: Unparsable techniques when there are error in cf-promises (cf-promises outputs error in stdout)

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://issues.rudder.io/issues/18178

### CODE REVIEW

**Comment by amousset** [comment]
python :boom:

**Comment by amousset** [comment]
what an enfer

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Comment by VinceMacBuche** [comment]
Everything is good python, 

Mutable variable, enumerate through index, break in loop, and wonderful splice syntax 

python/20

**Comment by VinceMacBuche** [comment]
PR updated with a new commit

**Pull request merged**
