### PR TITLE
Fixes #10575: putting a double quote in a technique in the "class" parameter generate an invalid rudder-reporting file for the agent

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://www.rudder-project.org/redmine/issues/10575

### CODE REVIEW

**Comment by ncharles** [comment]
Shouldn't you update one test to match this behaviour change ?

**Comment by VinceMacBuche** [comment]
Commit modified

**Comment by ncharles** [comment]
Great !

**Comment by VinceMacBuche** [comment]
OK, merging this PR

**Pull request merged**
