### PR TITLE
Fixes #15421: Add a file_check_line_absentGM 

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/15421

### CODE REVIEW

**Comment by Fdall** [comment]
Commit modified

**Comment by Fdall** [comment]
Commit modified

**Comment by Fdall** [comment]
Commit modified

**Comment by amousset** [comment]
Needs tests before merge.

**Comment by Fdall** [comment]
This was meant for cis plugin. It does not seem relevant anymore

**Pull request closed without merging**
